# Generated by Django 3.1.5 on 2021-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20210127_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='accum_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Емкость аккумулятора'),
        ),
    ]
