# Generated by Django 3.1.5 on 2021-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20210127_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='accum_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип аккумулятора'),
        ),
    ]
