# Generated by Django 3.1.5 on 2021-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20210127_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechmod',
            name='amount_of_acb',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество аккумуляторов'),
        ),
        migrations.AddField(
            model_name='mechmod',
            name='diameter',
            field=models.CharField(default=25, max_length=50, verbose_name='Диаметр посадки атомайзера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod',
            name='amount_of_acb',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество аккумуляторов'),
        ),
        migrations.AddField(
            model_name='mod',
            name='connector',
            field=models.CharField(default=510, max_length=255, verbose_name='Тип коннектора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod',
            name='diameter',
            field=models.CharField(default=25, max_length=50, verbose_name='Диаметр посадки атомайзера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod',
            name='thermal_control',
            field=models.BooleanField(default=False, verbose_name='Термоконтроль'),
        ),
    ]
