# Generated by Django 3.1.5 on 2021-02-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_auto_20210205_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
