# Generated by Django 3.1.5 on 2021-02-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_auto_20210208_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.cart', verbose_name='Корзина'),
        ),
    ]
